#!/usr/bin/env bash
# digs domain given

domain=$1

domain_full=`dig "$domain" | grep -A1 'ANSWER SECTION:' | tail +2 | awk 'BEGIN { FS="[\t]" } ; { print $1}'`
sub=`echo "$domain_full" | cut -d "." -f1`
rec=`dig "$domain" | grep -A1 'ANSWER SECTION:' | tail +2 | awk 'BEGIN { FS="[\t]" } ; { print $4}'`
ip=`dig "$domain" | grep -A1 'ANSWER SECTION:' | tail +2 | awk 'BEGIN { FS="[\t]" } ; { print $5}'`
echo "The subdomain $sub is a $rec record and points to $ip"
