#!/usr/bin/env bash
# displays Fizz Buzz.
Fi="Fizz"
Bu="Buzz"
FiBu="FizzBuzz"
for i in {1..100}
do
	if [ $(((i % 3) + (i % 5))) = 0 ]
	then
		echo "$FiBu"
	elif [ $((i % 3)) = 0 ]
	then
		echo "$Fi"
	elif [ $((i % 5)) = 0 ]
	then
		echo "$Bu"
	else
		echo "$i"
	fi
done
