#!/usr/bin/env bash
# print bad on 4 and good on 8.
i=1
M="Best School"
while [ $i -lt 11 ]
do
	
	if [ $i = 4 ]
	then
		echo "bad luck"
		elif [ $i = 8 ]
		then
			 echo "good luck"
	else
		echo "$M"
	fi
	let i++
done
