#!/usr/bin/env bash
# prints best school 10 times
FILE=school
if [ -f $FILE ];
then
	echo "$FILE file exists"
	if [ $(cat $FILE | wc -c) -gt 0 ];
	then
		echo "$FILE file is not empty"
	else
		echo "$FILE file is empty"
	fi
	echo "$FILE is a regular file"
elif [ -d $FILE ];
then
	echo "$FILE file exists"
	if [ $(ls $FILE -1 | wc -l) -gt 0 ];
	then
		echo "$FILE file is not empty"
	else
		echo "$FILE file is empty"
	fi
else
	echo "$FILE file does not exist"
fi
